-- AlterTable
ALTER TABLE `ClinicSettings` ADD COLUMN `mailFrom` VARCHAR(191) NULL,
    ADD COLUMN `smsFrom` VARCHAR(191) NULL,
    ADD COLUMN `smsProvider` VARCHAR(191) NOT NULL DEFAULT 'NONE',
    ADD COLUMN `smtpHost` VARCHAR(191) NULL,
    ADD COLUMN `smtpPass` VARCHAR(191) NULL,
    ADD COLUMN `smtpPort` INTEGER NOT NULL DEFAULT 587,
    ADD COLUMN `smtpUser` VARCHAR(191) NULL,
    ADD COLUMN `twilioSid` VARCHAR(191) NULL,
    ADD COLUMN `twilioToken` VARCHAR(191) NULL;
